rafce
const cardData = [
    { title: 'Card 1', image: 'https://via.placeholder.com/150', description: 'Description for card 1' },
    {
        title: 'Mint Julep', image: 'https://www.thecocktaildb.com/images/media/drink/squyyq1439907312.jpg',
        "strIngredient1": "Mint",
        "strIngredient2": "Bourbon",
        "strIngredient3": "Powdered sugar",
        "strIngredient4": "Water",
        "strIngredient5": null,
        "strIngredient6": null,
        "strIngredient7": null,
        "strIngredient8": null,
        "strMeasure1": "4 fresh ",
        "strMeasure2": "2 1/2 oz ",
        "strMeasure3": "1 tsp ",
        "strMeasure4": "2 tsp ",
        "strMeasure5": null,
        "strMeasure6": null,
        "strMeasure7": null,
        "strMeasure8": null,
        description: 'In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is well frosted. Garnish with a mint sprig.'
    },
    {
        title: 'Godchild', image: 'https://www.thecocktaildb.com/images/media/drink/m5nhtr1504820829.jpg',
        "strIngredient1": "Vodka",
        "strIngredient2": "Amaretto",
        "strIngredient3": "Heavy cream",
        "strIngredient4": null,
        "strIngredient5": null,
        "strIngredient6": null,
        "strIngredient7": null,
        "strIngredient8": null,
        "strMeasure1": "1 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "1 oz ",
        "strMeasure4": null,
        "strMeasure5": null,
        "strMeasure6": null,
        "strMeasure7": null,
        "strMeasure8": null,
        description: 'Shake all ingredients well with cracked ice, strain into a champagne flute, and serve.'
    },
    { title: 'Card 4', image: 'https://via.placeholder.com/150', description: 'Description for card 4' },
    { title: 'Card 5', image: 'https://via.placeholder.com/150', description: 'Description for card 5' },
    {
        title: 'Gin And Tonic', image: 'https://www.thecocktaildb.com/images/media/drink/k0508k1668422436.jpg',
        "strIngredient1": "Gin",
        "strIngredient2": "Tonic water",
        "strIngredient3": "Lime",
        "strIngredient4": null,
        "strIngredient5": null,
        "strIngredient6": null,
        "strIngredient7": null,
        "strIngredient8": null,
        "strMeasure1": "2 oz ",
        "strMeasure2": "5 oz ",
        "strMeasure3": "1 ",
        "strMeasure4": null,
        "strMeasure5": null,
        "strMeasure6": null,
        "strMeasure7": null,
        "strMeasure8": null,
        description: 'Pour the gin and the tonic water into a highball glass almost filled with ice cubes. Stir well. Garnish with the lime wedge.'
    },
    { title: 'Card 7', image: 'https://via.placeholder.com/150', description: 'Description for card 7' },
    { title: 'Card 8', image: 'https://via.placeholder.com/150', description: 'Description for card 8' },
];

export default cardData;